# Generated by Django 5.1.6 on 2025-02-12 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='shareable_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
