# Generated by Django 5.1.5 on 2025-02-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0003_remove_announcement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='default.mp3', upload_to='media/songs/'),
            preserve_default=False,
        ),
    ]
