# Generated by Django 5.1.5 on 2025-02-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0004_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='filepath',
        ),
    ]
