# Generated by Django 5.1.5 on 2025-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0005_remove_song_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
