# Generated by Django 5.1.5 on 2025-02-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0006_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
