# Generated by Django 5.1.6 on 2025-02-17 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0007_remove_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPlaylist',
            fields=[
                ('shared_playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_playlists', to='FytispoApp.playlist')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('playlist', 'shared_with')},
            },
        ),
    ]
