# Generated by Django 5.1.6 on 2025-02-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0008_sharedplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='shareable_uuid',
        ),
    ]
