# Generated by Django 5.1.6 on 2025-02-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FytispoApp', '0009_remove_playlist_shareable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='FytispoApp.content'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='flag_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_announcements', to='FytispoApp.flagreport'),
        ),
    ]
